- hosts: localhost
  gather_facts: false
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
  tasks:
  - name: Create In-memory Inventory
    add_host: 
      name: workstation-{{ OSP_GUID }}.{{ OSP_DOMAIN }}
      group: workstation
      ansible_user: "cloud-user"
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem

- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
    register: openstack_info
    tags:
       osp.smoke

  - name: Curl website
    uri:
      url: "http://{{ item.public_v4 }}"
      status_code: 200
      return_content: yes
    loop: "{{ openstack_info.openstack_servers }}"
    when: 'item.hostname == "frontend"'
    register: qa_webpage
    tags:
      - osp.smoke
    ignore_errors: True   

  - debug:
      var: qa_webpage

  - name: Fail if Ansible has done its job is not in the page content
    fail:
    when: 
      - 'item.skipped | default(false) == true'
      - '"Ansible has done its job" not in item.content'
    tags:
      - osp.smoke
    loop: "{{ qa_webpage.results }}"
