- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
      server: 'frontend'
    register: openstack_info
    tags:
       osp.smoke

  - name: Curl website
    uri:
      url: "http://{{ openstack_info.openstack_servers.0.public_v4 }}"
      status_code: 200
      return_content: yes
    register: qa_webpage
    tags:
      - osp.smoke
    ignore_errors: True   

  - debug:
      var: qa_webpage

  - fail:
      msg: "Not exist"
    when: 
      -   '"Ansible" not in qa_webpage.content' 
#  - name: Fail if Ansible has done its job is not in the page content
#    fail:
#    when: 
#      - 'item.skipped | default(false) == true'
#      - '"Ansible" not in item.content'
#    tags:
#      - osp.smoke
#    loop: "{{ qa_webpage.results }}"
