---
- name: install HAProxy
  yum:
    name: "{{ payload }}"
    state: latest

- name: start and enable HAProxy
  service:
    name: "{{ payload }}"
    state: started
    enabled: true

- name: configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: "restart {{ payload }}"
