---
- name: install tomcat
  package:
    name: "{{ payload }}"
    state: latest

- name: start and enable tomcat
  service:
    name: "{{ payload }}"
    state: started
    enabled: true

- name: create ansible tomcat directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: '0644'

